# Generated by Django 5.1.7 on 2025-03-23 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_table',
            name='user_type',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
